// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7z_WNpRmlYhjKRxLf1SjtVWPRPMohGM',
    appId: '1:1092889381807:android:9c6c09b82aad21e04d3d5a',
    messagingSenderId: '1092889381807',
    projectId: 'flutter-example-project-3cbd6',
    databaseURL: 'https://flutter-example-project-3cbd6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-example-project-3cbd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB4iQZXqJKuW_JAwVFKQ95ITufvUgTkuo',
    appId: '1:1092889381807:ios:fd298df835f891b64d3d5a',
    messagingSenderId: '1092889381807',
    projectId: 'flutter-example-project-3cbd6',
    databaseURL: 'https://flutter-example-project-3cbd6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-example-project-3cbd6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
